//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_USERS
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string telepon { get; set; }
        public string password { get; set; }
        public string role_id { get; set; }
        public string device_id { get; set; }
        public string web_id { get; set; }
        public string otp { get; set; }
        public string pin { get; set; }
        public string refresh_token { get; set; }
        public string fcm_token { get; set; }
        public Nullable<int> invalid_login { get; set; }
        public Nullable<int> reset_password { get; set; }
        public string avatar { get; set; }
        public Nullable<int> status { get; set; }
        public string company_id { get; set; }
        public string general_id { get; set; }
        public string customer_id { get; set; }
        public string user_erp { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> last_updated_at { get; set; }
        public string created_by { get; set; }
    }
}
