//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_DT_MATERIAL_SUMMARY
    {
        public int id { get; set; }
        public string operation_id { get; set; }
        public string so_id { get; set; }
        public string variant_name { get; set; }
        public decimal wide { get; set; }
        public int qty { get; set; }
        public decimal meter_kubik { get; set; }
        public decimal @long { get; set; }
    }
}
