//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_DT_MATERIAL_BOM
    {
        public string product_id_header { get; set; }
        public string bom_id { get; set; }
        public string product_id { get; set; }
        public string product_name { get; set; }
        public int on_hand_stock { get; set; }
        public int quantity { get; set; }
        public string allow_material_finish_good { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
