//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_GET_PRODUCT_BOM
    {
        public int id { get; set; }
        public string company_id { get; set; }
        public string company_name { get; set; }
        public string group_item_id { get; set; }
        public string item_id { get; set; }
        public string product_id { get; set; }
        public string supplier_id { get; set; }
        public string alias_customer { get; set; }
        public string measurement { get; set; }
    }
}
