//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_GROUP_ITEM
    {
        public string item_id { get; set; }
        public string product_name { get; set; }
        public int minimum_stock { get; set; }
        public int on_hand_stock { get; set; }
        public int stok_in { get; set; }
        public int stok_out { get; set; }
        public int stok { get; set; }
    }
}
