//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_GET_DATA_ITEM_SO
    {
        public int id { get; set; }
        public string company_id { get; set; }
        public string external_id { get; set; }
        public string item_code_1 { get; set; }
        public string item_code_2 { get; set; }
        public string item_code_3 { get; set; }
        public string item_code_4 { get; set; }
        public string item_code_5 { get; set; }
        public string item_code_6 { get; set; }
        public string uom_id { get; set; }
        public int status { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime last_updated_at { get; set; }
        public string created_by { get; set; }
        public string item_id { get; set; }
    }
}
