//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_LIST_COUNT_STOCK_OPNAME_COVER
    {
        public int id { get; set; }
        public string barcode { get; set; }
        public string product_id { get; set; }
        public string stockopname_id { get; set; }
        public int qty { get; set; }
    }
}
