//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_LIST_DT_QTY_SCAN_OUT_STOCK_OPNAME
    {
        public int id { get; set; }
        public string product_id { get; set; }
        public string barcode_qr_code { get; set; }
        public string create_at_qr_code { get; set; }
        public string id_stock { get; set; }
    }
}
