//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_REPORT_CALCULATE_LOG_STOCK_MOVE
    {
        public string product_id { get; set; }
        public string wh_id { get; set; }
        public string company_id { get; set; }
        public int stock_after { get; set; }
        public string product_name { get; set; }
        public string product_category_id { get; set; }
        public System.DateTime move_date { get; set; }
        public string product_category_name { get; set; }
        public int stock_before { get; set; }
        public int qty_done { get; set; }
        public System.DateTime updated_at { get; set; }
        public string scan_status { get; set; }
        public string product_group_id { get; set; }
        public string product_group_name { get; set; }
        public string allow_material_finish_good { get; set; }
    }
}
