//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_REPORT_CALCULATE_LOG_STOCK_MOVE_WAREHOUSE
    {
        public string wh_id { get; set; }
        public string company_id { get; set; }
        public int stock_after { get; set; }
    }
}
