//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_RPT_STOCK
    {
        public string product_group_id { get; set; }
        public string product_item { get; set; }
        public int stock { get; set; }
        public int scan_in { get; set; }
        public int scan_out { get; set; }
    }
}
