//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_SUMARY_STOCK_LONG_WIDE
    {
        public string item_id { get; set; }
        public string product_name { get; set; }
        public string product_item { get; set; }
        public int minimum_stock { get; set; }
        public int on_hand_stock { get; set; }
        public int stok_in { get; set; }
        public int stok_out { get; set; }
        public int stok { get; set; }
        public decimal on_hand_stock_m3 { get; set; }
        public decimal stok_in_m3 { get; set; }
        public decimal stok_out_m3 { get; set; }
        public decimal stok_m3 { get; set; }
        public decimal panjang { get; set; }
        public decimal lebar { get; set; }
        public decimal tinggi { get; set; }
        public string dimensi { get; set; }
    }
}
