//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_SUMARY_STOCK_LONG_WIDE_BLOCK_EXPORT
    {
        public string product_item { get; set; }
        public string product_name { get; set; }
        public string item_id { get; set; }
        public string size { get; set; }
        public int minimum_stock { get; set; }
        public int on_hand_stock { get; set; }
        public int stock_in { get; set; }
        public int stock_out { get; set; }
        public int stock { get; set; }
        public int bulan { get; set; }
        public int tahun { get; set; }
    }
}
