//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    
    public partial class SP_WORK_ORDER_ASSEMBLY_LIST
    {
        public int id { get; set; }
        public string operation_id { get; set; }
        public System.DateTime operation_date { get; set; }
        public string operation_date_str { get; set; }
        public int hd_operation_status { get; set; }
        public string hd_operation_status_name { get; set; }
        public string company_id { get; set; }
        public string company_name { get; set; }
        public bool priority_status { get; set; }
        public bool work_order_internal { get; set; }
        public string note_close { get; set; }
    }
}
