//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACCESS_DATA
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string wh_id { get; set; }
        public string product_group_id { get; set; }
        public string product_category_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> last_updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string created_by { get; set; }
    }
}
