//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_DASHBOARD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LOGIN
    {
        public int id { get; set; }
        public string company_id { get; set; }
        public string user_id { get; set; }
        public string user_erp { get; set; }
        public string general_id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string telepon { get; set; }
        public string password { get; set; }
        public Nullable<int> invalid_login { get; set; }
        public Nullable<int> reset_password { get; set; }
        public string role_id { get; set; }
        public string role { get; set; }
        public Nullable<int> status { get; set; }
    }
}
