// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_API_WARRANTY_TSJ.ModelsDBERP
{
    public partial class MsLogLogin
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public DateTime? LoginAt { get; set; }
        public int? LoginStatus { get; set; }
        public string Message { get; set; }
    }
}