// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_API_WARRANTY_TSJ.ModelsDBERP
{
    public partial class VLogin
    {
        public int Id { get; set; }
        public string CompanyId { get; set; }
        public string UserId { get; set; }
        public string UserErp { get; set; }
        public string GeneralId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Telepon { get; set; }
        public string Password { get; set; }
        public int? InvalidLogin { get; set; }
        public int? ResetPassword { get; set; }
        public string RoleId { get; set; }
        public string Role { get; set; }
        public int? Status { get; set; }
    }
}