// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_API_WARRANTY_TSJ.ModelsDBERP
{
    public partial class VUser
    {
        public int Id { get; set; }
        public string CompanyId { get; set; }
        public string UserId { get; set; }
        public string RoleId { get; set; }
        public string ParentId { get; set; }
        public string ParentName { get; set; }
        public string ParentPhone { get; set; }
        public string GeneralId { get; set; }
        public string UserErp { get; set; }
        public string Role { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Telepon { get; set; }
        public string DeviceId { get; set; }
        public string FcmToken { get; set; }
        public string RefreshToken { get; set; }
        public int? InvalidLogin { get; set; }
        public int? ResetPassword { get; set; }
        public string Avatar { get; set; }
        public int? Status { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTime? LastUpdatedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}