// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_API_WARRANTY_TSJ.Models
{
    public partial class BarcodeSerialQr
    {
        public long Id { get; set; }
        public string SerialQrId { get; set; }
        public string SerialCode { get; set; }
        public string RegistrationCode { get; set; }
        public string Source { get; set; }
        public int? TotalPrint { get; set; }
        public bool? Active { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTime? DeletedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}