// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_API_WARRANTY_TSJ.Models
{
    public partial class LogError
    {
        public long Id { get; set; }
        public string ServiceName { get; set; }
        public string ServiceError { get; set; }
        public string LogJson { get; set; }
        public DateTime? ErrorDate { get; set; }
        public string CreatedBy { get; set; }
    }
}