// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_API_WARRANTY_TSJ.Models
{
    public partial class LogRequestActivation
    {
        public long Id { get; set; }
        public string LogRequestId { get; set; }
        public string LogJsonActivation { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}