// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_API_WARRANTY_TSJ.Models
{
    public partial class TemplatePrint
    {
        public long Id { get; set; }
        public string TemplateName { get; set; }
        public string Base64Logo { get; set; }
        public string Source { get; set; }
        public bool? Active { get; set; }
        public bool? PrintDefault { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}